name: CI/CD for EventEase

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install flask

    - name: Run Flask app (test only)
      run: |
        python backend/app.py &
        sleep 5
        curl http://localhost:5000 || echo "App did not respond"
